# Generated by Django 4.2.15 on 2024-12-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total',
        ),
    ]
